// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://btodnwnqfowcjnedpagh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0b2Rud25xZm93Y2puZWRwYWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTQwMTIsImV4cCI6MjA4Nzc3MDAxMn0.EDLKiS9sABmTipsEfSDoVym2Sc3LWW7Z-MWgy0FsrX4";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);